### PR TITLE
Replacing pin_created with pin_hash

### LINKED ISSUE #542: pins_reactive_read does not update when pin changes more frequently than once a minute
the `pin_reactive_read` function sets up a `shiny::reactivePoll` object using `pin_created` as the `checkFunc`.  However, this is not ideal, because `pin_created` only seems to return a timestamp with accuracy to the minute, and so if a pin is updated twice within the same minute, the reactive is never triggered.  Wouldn't it make more sense to use the hash value?  Here is an example shiny app. 

``` r
pin_hash <- function(name, board) pins::pin_meta(board, name)$pin_hash

custom_pin_reactive_read <- function(board, name, interval) {
  rlang::check_installed("shiny")
  shiny::reactivePoll(intervalMillis = interval, 
                      session = shiny::getDefaultReactiveDomain(), 
                      checkFunc = function() pin_hash(name = name, board = board), 
                      valueFunc = function() pins::pin_read(board = board, name = name))
}

write_time_pin <- function(board) pins::pin_write(board, Sys.time(), "time")

ui <- shiny::fluidPage(shiny::textOutput("pins"),
                       shiny::textOutput("custom"))

server <- function(input, output, session) {
  board <- pins::board_temp()
  write_time_pin(board)
  # update pin once every second
  observe({ 
    write_time_pin(board)
    shiny::invalidateLater(1000)
  })
  
  pins_pin_reactive_read_value <- pins::pin_reactive_read(board = board, "time", 1000)
  custom_pin_reactive_read_value <- custom_pin_reactive_read(board = board, "time", 1000)
  output$pins <- shiny::renderPrint(req(pins_pin_reactive_read_value()))
  output$custom <- shiny::renderPrint(req(custom_pin_reactive_read_value()))
}

shiny::shinyApp(ui, server)
```

### PR DESCRIPTION
**Pull request by thomaszwagerman**
Replaces `pin_created()` with `pin_hash()`, which supports functionality of `pin_reactive_read()` and `pin_reactive_download()`.

Suggestion made by @TylerGrantSmith.

Closes #542

### CODE REVIEW

**Comment by thomaszwagerman** [comment]
Looking at this again and had a thought.

I've replaced `pin_created()` with a function called `pin_hash()`, however where `pin_meta()` returns `$created` for the date the pin was created, for the hash of the pin contents it returns `$pin_hash`. When I looked back over the code this caused confusion.

Either I change the `pin_hash()` function name, or the output of `pin_meta()` should be changed from `$pin_hash` -> `$hash`, which I think is more consistent with the rest of `pin_meta()`'s outputs.

**Comment by juliasilge** [comment]
Thank you so much for this PR @thomaszwagerman and for your patience on it!

I agree that it's not ideal that the hash is called `pin_hash` in the pin metadata. However, it wouldn't really solve this specific question because there is an existing unexported function called `pin_hash()`:

https://github.com/rstudio/pins-r/blob/9d014de4d9384213ebc4e6e02888de5eb36d4ffd/R/pin-read-write.R#L209-L216

Even if we were to change the name of `pin_hash`, we still need to change the function name here. Maybe `get_pin_hash()`?

**Comment by thomaszwagerman** [comment]
Hi @juliasilge, thank you for you reply, and no worries at all for the wait!

Apologies, I was not aware of the unexported `pin_hash()` - I've implemented your suggestion by changing the function name to `get_pin_hash()`.

**Review by juliasilge — APPROVED** [review]
Thank you so much for this PR @thomaszwagerman! 🙌

**Pull request merged**
